run_group: debug
seed: 0
env_name: pointmaze-medium-navigate-v0
working_dir: exp
restore_path: null
restore_epoch: null

agent:
  agent_name: gcbc

finetune:
  horizon: 1
  eq_quantile: 0.6
  mc_quantile: 0.9
  filter_by_mc: false
  filter_by_td: false
  filter_by_equality: false
  filter_by_start: false
  filter_by_heuristic: true

train_steps: 1000000
log_interval: 5000
eval_interval: 100000
save_interval: 1000000

eval_tasks: null
eval_episodes: 50
eval_temperature: 0
eval_gaussian: null
video_episodes: 0
video_frame_skip: 3
eval_on_cpu: 1

finetune_steps: 10
finetune_lr: 3.e-5
